import type { Locale } from '../i18n/messages'

/** Bilingual fields for dev blog posts (add new posts here). */
export type LocalizedText = Record<Locale, string>

export type DevBlogPost = {
  slug: string
  /** ISO `YYYY-MM-DD` for sorting and display */
  date: string
  title: LocalizedText
  excerpt: LocalizedText
  /** Full Markdown body per locale */
  body: LocalizedText
}

export const DEV_BLOG_POSTS: DevBlogPost[] = [
  {
    slug: 'yt2bili-desktop-alpha-1',
    date: '2026-09-20',
    title: {
      zh: 'yt2bili 桌面一期：0.2.0-alpha.1 完成工程验收',
      'zh-HK': 'yt2bili 桌面一期：0.2.0-alpha.1 完成工程驗收',
      en: 'yt2bili desktop phase 1: 0.2.0-alpha.1 passes engineering acceptance',
    },
    excerpt: {
      zh:
        '桌面开发版已实现任务中心、账号与连接、设置、预览确认投稿、持续调度和恢复机制，并通过本地自动化与原生通信验证。',
      'zh-HK':
        '桌面開發版已實現任務中心、帳號與連線、設定、預覽確認投稿、持續排程和恢復機制，並通過本機自動化與原生通訊驗證。',
      en:
        'The desktop development build now includes tasks, accounts, settings, preview-confirmed submission, persistent scheduling, and recovery, with local automation and native IPC checks passing.',
    },
    body: {
      zh: [
        'yt2bili 桌面端第一期已经形成可运行的开发版本，阶段版本为 **`0.2.0-alpha.1`**。它没有另写一套下载和投稿逻辑，而是用 React、TypeScript 与 Tauri 连接现有 Python 业务核心。',
        '',
        '> **状态说明：** 本次完成的是本地工程实现和模拟验收。没有读取现有账号密钥、执行真实登录或真实投稿；外部平台链路仍需用户使用自己的账号和授权素材补验。',
        '',
        '## 已实现的桌面工作流',
        '',
        '- StarDazz 黑白灰视觉、浅色/深色/系统主题，以及最小 `1024×680` 的原生 Tauri 窗口。',
        '- 任务列表、搜索筛选、分页、阶段状态、下载与校验进度、详情、封面、原文译文和日志。',
        '- 单条或批量链接、TXT 导入、默认预览、元数据编辑、确认投稿、重试、取消、结果核对和只修复素材。',
        '- B 站扫码登录与登录文件导入、DeepL 系统凭据、YouTube Cookie、首次配置向导、工具诊断和日志导出。',
        '- 持续三阶段调度、数据库迁移备份、任务恢复、操作去重、文件锁、账号上传互斥和后台子进程回收。',
        '- Python 冻结脚本、离线媒体自检、原生通信自检和 Windows CI 配置。',
        '',
        '![yt2bili 深色主题任务中心](/yt2bili/tasks-dark.png)',
        '',
        '界面中的任务为示例数据，并明确显示预览标识，不代表真实投稿记录。',
        '',
        '## 本次验证',
        '',
        '- 原有 **62 项 Python 回归测试**通过。',
        '- 新增 **23 项桌面后台测试**通过，覆盖协议、并发调度、取消恢复、未知投稿结果、媒体重试、配置脱敏、数据库备份、共享目录锁、日志和二维码状态。',
        '- **5 项浏览器交互测试**通过，覆盖首次配置、空状态、预览门禁、轮询一致性、主题和最小窗口布局。',
        '- React TypeScript 检查、Vite 生产构建、Tauri Windows 调试构建与前端—Rust—Python 原生通信检查通过。',
        '- Windows 启动路径问题修复后增加 **3 项环境回归测试**，并以 `npm run desktop` 和根目录启动脚本完成实机启动验证。',
        '',
        '冻结后台已在隔离目录中完成协议请求和本地生成视频的 dry-run，达到 `ready` 且没有投稿。生产构建不包含开发示例任务模块。',
        '',
        '## 仍待补验',
        '',
        '需要用户在桌面应用内用自己的 DeepL 与 B 站账号完成扫码、Cookie 刷新、YouTube 下载、实际翻译和一次授权素材投稿，并核对 BV 号与清理行为。多显示器、更多 Windows DPI 档位以及 macOS 真机也尚未验收。签名 Windows 安装包、DMG 和 Apple 公证仍属于后续阶段。',
        '',
        '## 当前待办与下一项产品改造',
        '',
        '当前 Bug 清单会先处理任务筛选数字、校验进度更新频率、等待中统计、上传间隔输入框、启动速度、DeepL 额度处理，以及新建任务默认值。',
        '',
        '最高优先级的新需求是**双 B 站账号上传与单链接任务**：保留一条共享下载队列和一条共享校验队列，为两个账号各设一条独立上传队列；每次创建只接受一个 YouTube 链接并要求明确选择目标账号。同一视频可以分别投向两个账号，但必须成为两条隔离任务。',
        '',
        '> 双账号内容目前是 **PRD 目标需求，不是已经实现或验证的功能**。它需要新的账号身份、`task_id`、数据库迁移、素材隔离、账号级锁与间隔，以及真实双账号冒烟测试。',
        '',
        '阶段状态与后续平台交付见[路线图](/roadmap)，代码与实际完成状态以 [yt2bili GitHub 仓库](https://github.com/YihanLi-erisaer/yt2bili)为准。',
      ].join('\n'),
      'zh-HK': [
        'yt2bili 桌面端第一期已經形成可運行的開發版本，階段版本為 **`0.2.0-alpha.1`**。它沒有另寫一套下載和投稿邏輯，而是用 React、TypeScript 與 Tauri 連接現有 Python 業務核心。',
        '',
        '> **狀態說明：** 本次完成的是本機工程實作和模擬驗收。沒有讀取現有帳號金鑰、執行真實登入或真實投稿；外部平台鏈路仍需使用者使用自己的帳號和授權素材補驗。',
        '',
        '## 已實現的桌面工作流程',
        '',
        '- StarDazz 黑白灰視覺、淺色/深色/系統主題，以及最小 `1024×680` 的原生 Tauri 視窗。',
        '- 任務清單、搜尋篩選、分頁、階段狀態、下載與驗證進度、詳情、封面、原文譯文和日誌。',
        '- 單條或批次連結、TXT 匯入、預設預覽、中繼資料編輯、確認投稿、重試、取消、結果核對和只修復素材。',
        '- B 站掃碼登入與登入檔案匯入、DeepL 系統憑據、YouTube Cookie、首次設定精靈、工具診斷和日誌匯出。',
        '- 持續三階段排程、資料庫遷移備份、任務恢復、操作去重、檔案鎖、帳號上傳互斥和背景子程序回收。',
        '- Python 凍結指令碼、離線媒體自檢、原生通訊自檢和 Windows CI 設定。',
        '',
        '![yt2bili 深色主題任務中心](/yt2bili/tasks-dark.png)',
        '',
        '介面中的任務為示例資料，並明確顯示預覽標識，不代表真實投稿紀錄。',
        '',
        '## 本次驗證',
        '',
        '- 原有 **62 項 Python 回歸測試**通過。',
        '- 新增 **23 項桌面後台測試**通過，涵蓋協議、並行排程、取消恢復、未知投稿結果、媒體重試、設定脫敏、資料庫備份、共用目錄鎖、日誌和二維碼狀態。',
        '- **5 項瀏覽器互動測試**通過，涵蓋首次設定、空狀態、預覽門禁、輪詢一致性、主題和最小視窗佈局。',
        '- React TypeScript 檢查、Vite 生產構建、Tauri Windows 偵錯構建與前端—Rust—Python 原生通訊檢查通過。',
        '- Windows 啟動路徑問題修復後增加 **3 項環境回歸測試**，並以 `npm run desktop` 和根目錄啟動指令碼完成實機啟動驗證。',
        '',
        '凍結後台已在隔離目錄中完成協議請求和本機產生影片的 dry-run，達到 `ready` 且沒有投稿。生產構建不包含開發示例任務模組。',
        '',
        '## 仍待補驗',
        '',
        '需要使用者在桌面應用程式內用自己的 DeepL 與 B 站帳號完成掃碼、Cookie 重新整理、YouTube 下載、實際翻譯和一次授權素材投稿，並核對 BV 號與清理行為。多顯示器、更多 Windows DPI 檔位以及 macOS 真機也尚未驗收。簽署 Windows 安裝套件、DMG 和 Apple 公證仍屬於後續階段。',
        '',
        '## 目前待辦與下一項產品改造',
        '',
        '目前 Bug 清單會先處理任務篩選數字、驗證進度更新頻率、等待中統計、上傳間隔輸入框、啟動速度、DeepL 額度處理，以及新建任務預設值。',
        '',
        '最高優先級的新需求是**雙 B 站帳號上傳與單連結任務**：保留一條共用下載佇列和一條共用驗證佇列，為兩個帳號各設一條獨立上傳佇列；每次建立只接受一個 YouTube 連結並要求明確選擇目標帳號。同一影片可以分別投向兩個帳號，但必須成為兩條隔離任務。',
        '',
        '> 雙帳號內容目前是 **PRD 目標需求，不是已經實現或驗證的功能**。它需要新的帳號身份、`task_id`、資料庫遷移、素材隔離、帳號級鎖與間隔，以及真實雙帳號冒煙測試。',
        '',
        '階段狀態與後續平台交付見[路線圖](/roadmap)，程式碼與實際完成狀態以 [yt2bili GitHub 倉庫](https://github.com/YihanLi-erisaer/yt2bili)為準。',
      ].join('\n'),
      en: [
        'yt2bili desktop phase 1 is now a runnable development build, version **`0.2.0-alpha.1`**. It does not introduce a second download and submission stack: React, TypeScript, and Tauri connect to the existing Python business core.',
        '',
        '> **Status:** this milestone covers local engineering implementation and simulated acceptance. It did not read existing account secrets, perform a real login, or submit real media. The external platform path still requires user-run validation with personal accounts and authorized material.',
        '',
        '## Implemented desktop workflow',
        '',
        '- StarDazz’s neutral visual system, light/dark/system themes, and a native Tauri window down to `1024×680`.',
        '- Task list, search and filters, pagination, stage status, download and validation progress, details, covers, source and translated text, and logs.',
        '- Single or batch links, TXT import, preview by default, metadata editing, confirmed submission, retry, cancel, result resolution, and media-only repair.',
        '- Bilibili QR login and login-file import, system credential storage for DeepL, YouTube cookies, first-run setup, tool diagnostics, and log export.',
        '- Persistent three-stage scheduling, database migration backups, task recovery, operation deduplication, file locks, account upload exclusion, and child-process cleanup.',
        '- Python freezing scripts, offline media self-checks, native IPC smoke checks, and Windows CI configuration.',
        '',
        '![yt2bili task center in the dark theme](/yt2bili/tasks-dark.png)',
        '',
        'The UI uses sample tasks and displays a preview marker; it is not real submission history.',
        '',
        '## Verification completed',
        '',
        '- The existing **62 Python regression tests** passed.',
        '- **23 new desktop-backend tests** passed across protocol handling, concurrent scheduling, cancellation and recovery, unknown submission results, media retries, redaction, database backups, shared-directory locks, logs, and QR states.',
        '- **5 browser interaction tests** passed across first-run setup, empty state, preview gates, polling consistency, themes, and the minimum window layout.',
        '- React TypeScript checks, the Vite production build, a native Tauri Windows debug build, and frontend—Rust—Python IPC checks passed.',
        '- After fixing Windows launch-path handling, **3 environment regression tests** were added, and both `npm run desktop` and the root launch script started the native app successfully.',
        '',
        'The frozen worker also handled protocol requests and a dry run with locally generated media in an isolated directory, reached `ready`, and did not submit. Production output excludes the development sample-task module.',
        '',
        '## Validation still pending',
        '',
        'A user still needs to test QR login, cookie refresh, YouTube download, live translation, and one authorized submission with their own DeepL and Bilibili accounts, then verify the BV ID and cleanup behavior. Multi-monitor behavior, more Windows DPI levels, and real macOS hardware also remain untested. Signed Windows installers, DMGs, and Apple notarization belong to later phases.',
        '',
        '## Current backlog and next product change',
        '',
        'The current bug list covers filtered task counts, validation update cadence, waiting counts, the upload-gap input, startup speed, DeepL quota handling, and new-task defaults.',
        '',
        'The highest-priority new requirement is **dual Bilibili accounts with single-link tasks**: keep one shared download queue and one shared validation queue, but give each of two accounts its own upload queue. Each create action accepts one YouTube link and requires an explicit target account. The same video may go to both accounts only as two isolated tasks.',
        '',
        '> Dual-account support is currently a **PRD target, not an implemented or verified feature**. It requires new account identities, `task_id`, database migration, isolated media directories, per-account locks and cooldowns, and a real two-account smoke test.',
        '',
        'See the [roadmap](/roadmap) for milestone status and later platform delivery. Code and actual completion status remain authoritative in the [yt2bili GitHub repository](https://github.com/YihanLi-erisaer/yt2bili).',
      ].join('\n'),
    },
  },
  {
    slug: 'yt2bili-desktop-roadmap',
    date: '2026-09-19',
    title: {
      zh: 'yt2bili：从命令行走向跨平台桌面应用',
      'zh-HK': 'yt2bili：從命令列走向跨平台桌面應用程式',
      en: 'yt2bili: from CLI to a cross-platform desktop app',
    },
    excerpt: {
      zh:
        '完成三期桌面端实施方案：先交付可视化工作流，再制作 Windows 安装程序，最后发布 Apple Silicon 与 Intel 两套 macOS DMG。',
      'zh-HK':
        '完成三期桌面端實施方案：先交付視覺化工作流程，再製作 Windows 安裝程式，最後發布 Apple Silicon 與 Intel 兩套 macOS DMG。',
      en:
        'A three-phase desktop plan: ship the visual workflow first, package a Windows installer next, then release separate Apple Silicon and Intel macOS DMGs.',
    },
    body: {
      zh: [
        'yt2bili 已经具备下载、翻译、完整媒体校验、队列投稿、失败重试和修复能力。下一阶段不是重写这些功能，而是把同一套 Python 业务核心放进更清晰、可恢复的桌面工作流。',
        '',
        '> **当前状态：** 本次完成的是工程实施方案与公开路线图。桌面界面、安装包和 macOS 应用尚未实现，也没有在本次规划中执行投稿。',
        '',
        '## 技术路线',
        '',
        '主方案采用 **React + TypeScript + Vite + Tauri 2 + Python worker**：',
        '',
        '- React/TypeScript 负责延续 StarDazz 官网风格的任务、登录、设置和素材预览界面。',
        '- Tauri 负责窗口、系统目录、文件选择、凭据访问、单实例控制和安装包。',
        '- Python 继续运行 yt-dlp、DeepL、FFmpeg、biliup、SQLite 和现有三阶段队列。',
        '- 桌面主进程与 worker 使用版本化 JSON Lines 管道通信，不开放本地 HTTP 端口。',
        '',
        '第一期就会处理安装版最容易暴露的问题：把用户数据移出源码目录，统一工具发现和子进程管理，把终端输出改成结构化事件，并为 GUI 与 CLI 增加共享的跨进程投稿锁。',
        '',
        '## 三期交付',
        '',
        '### 第一期：可视化操作界面',
        '',
        '预计 **15～21 个工作日**，目标版本 `0.2.0-alpha`。交付真实桌面开发版，覆盖配置、B 站扫码登录、批量任务、进度与日志、素材预览和编辑、确认投稿、取消恢复、重试与修复。默认流程先准备素材并预览，不会在用户未确认时自动投稿。',
        '',
        '### 第二期：Windows 安装程序',
        '',
        '预计 **6～9 个工作日**，目标版本 `0.3.0`。冻结 Python worker 与 FFmpeg、biliup、Deno 等依赖，通过 Tauri NSIS 交付 `setup.exe`，完成 WebView2、签名、升级、卸载、哈希和干净 Windows 环境验收。用户不需要自行安装 Python、Rust、Node.js 或 FFmpeg。',
        '',
        '### 第三期：macOS 应用与 DMG',
        '',
        '预计 **7～11 个工作日**，目标版本 `0.4.0`。分别构建 Apple Silicon 与 Intel 原生包，完成 Keychain、Finder 启动、`.app`/DMG 布局、嵌套签名、公证和 Gatekeeper 实机验证；不以 arm64 包代替 Intel 验收。',
        '',
        '三期总估算约 **28～41 个工作日**，不含证书申请、平台审批等待和大范围需求变更。',
        '',
        '## 不会牺牲的安全边界',
        '',
        '- 下载、校验、上传各保持单路，跨阶段并行；不增加上传并发设置。',
        '- 完整 MP4 继续直接复用，非 MP4 才转换，不为界面体验自动降画质。',
        '- 校验失败不得上传；获得 BV 号后才允许清理任务素材。',
        '- 上传结果未知时进入待核对状态，不自动重投。',
        '- `repair` 只准备替换素材，不重新投稿，也不改写原 BV 号。',
        '- CLI 继续保留，并与桌面端共用业务层和投稿约束。',
        '',
        '完整分期内容见[公开路线图](/roadmap)。实际完成状态与未来发行版以 [yt2bili GitHub 仓库](https://github.com/YihanLi-erisaer/yt2bili)为准。',
      ].join('\n'),
      'zh-HK': [
        'yt2bili 已經具備下載、翻譯、完整媒體驗證、佇列投稿、失敗重試和修復能力。下一階段不是重寫這些功能，而是把同一套 Python 業務核心放進更清晰、可恢復的桌面工作流程。',
        '',
        '> **目前狀態：** 本次完成的是工程實施方案與公開路線圖。桌面介面、安裝套件和 macOS 應用程式尚未實現，也沒有在本次規劃中執行投稿。',
        '',
        '## 技術路線',
        '',
        '主方案採用 **React + TypeScript + Vite + Tauri 2 + Python worker**：',
        '',
        '- React/TypeScript 負責延續 StarDazz 官網風格的任務、登入、設定和素材預覽介面。',
        '- Tauri 負責視窗、系統目錄、檔案選擇、憑據存取、單一執行個體控制和安裝套件。',
        '- Python 繼續運行 yt-dlp、DeepL、FFmpeg、biliup、SQLite 和現有三階段佇列。',
        '- 桌面主程序與 worker 使用版本化 JSON Lines 管道通訊，不開放本機 HTTP 連接埠。',
        '',
        '第一期就會處理安裝版最容易暴露的問題：把使用者資料移出原始碼目錄，統一工具發現和子程序管理，把終端輸出改成結構化事件，並為 GUI 與 CLI 增加共用的跨程序投稿鎖。',
        '',
        '## 三期交付',
        '',
        '### 第一期：視覺化操作介面',
        '',
        '預計 **15～21 個工作日**，目標版本 `0.2.0-alpha`。交付真實桌面開發版，涵蓋設定、B 站掃碼登入、批次任務、進度與日誌、素材預覽和編輯、確認投稿、取消恢復、重試與修復。預設流程先準備素材並預覽，不會在使用者未確認時自動投稿。',
        '',
        '### 第二期：Windows 安裝程式',
        '',
        '預計 **6～9 個工作日**，目標版本 `0.3.0`。凍結 Python worker 與 FFmpeg、biliup、Deno 等依賴，透過 Tauri NSIS 交付 `setup.exe`，完成 WebView2、簽署、升級、解除安裝、雜湊和乾淨 Windows 環境驗收。使用者不需要自行安裝 Python、Rust、Node.js 或 FFmpeg。',
        '',
        '### 第三期：macOS 應用程式與 DMG',
        '',
        '預計 **7～11 個工作日**，目標版本 `0.4.0`。分別構建 Apple Silicon 與 Intel 原生套件，完成 Keychain、Finder 啟動、`.app`/DMG 佈局、巢狀簽署、公證和 Gatekeeper 實機驗證；不以 arm64 套件代替 Intel 驗收。',
        '',
        '三期總估算約 **28～41 個工作日**，不含憑證申請、平台審批等待和大範圍需求變更。',
        '',
        '## 不會犧牲的安全邊界',
        '',
        '- 下載、驗證、上傳各保持單路，跨階段並行；不增加上傳並行設定。',
        '- 完整 MP4 繼續直接重用，非 MP4 才轉換，不為介面體驗自動降低畫質。',
        '- 驗證失敗不得上傳；取得 BV 號後才允許清理任務素材。',
        '- 上傳結果未知時進入待核對狀態，不自動重新投稿。',
        '- `repair` 只準備替換素材，不重新投稿，也不改寫原 BV 號。',
        '- CLI 繼續保留，並與桌面端共用業務層和投稿約束。',
        '',
        '完整分期內容見[公開路線圖](/roadmap)。實際完成狀態與未來發行版以 [yt2bili GitHub 倉庫](https://github.com/YihanLi-erisaer/yt2bili)為準。',
      ].join('\n'),
      en: [
        'yt2bili already handles downloading, translation, full media validation, queued submissions, retries, and repair. The next step is not to rewrite that work; it is to place the same Python core inside a clearer, recoverable desktop workflow.',
        '',
        '> **Current status:** this update delivers an engineering plan and public roadmap. The desktop UI, installers, and macOS apps have not been implemented, and no submission was performed as part of this planning work.',
        '',
        '## Technical direction',
        '',
        'The primary stack is **React + TypeScript + Vite + Tauri 2 + a Python worker**:',
        '',
        '- React and TypeScript provide task, login, settings, and media-preview screens in the StarDazz visual language.',
        '- Tauri owns windows, system paths, file pickers, credential access, single-instance behavior, and installers.',
        '- Python continues to run yt-dlp, DeepL, FFmpeg, biliup, SQLite, and the existing three-stage queues.',
        '- The desktop process and worker communicate over a versioned JSON Lines pipe; no local HTTP port is exposed.',
        '',
        'Phase 1 addresses packaging risks early: move user data out of the source tree, centralize tool and child-process management, replace terminal-only output with structured events, and add a shared cross-process upload lock for both GUI and CLI.',
        '',
        '## Three delivery phases',
        '',
        '### Phase 1: visual workflow',
        '',
        'Estimated at **15–21 working days**, targeting `0.2.0-alpha`. The development build will cover setup, Bilibili QR login, batch tasks, progress and logs, media preview and editing, confirmed submission, cancellation and recovery, retry, and repair. The default flow prepares a preview and never submits before the user confirms.',
        '',
        '### Phase 2: Windows installer',
        '',
        'Estimated at **6–9 working days**, targeting `0.3.0`. Freeze the Python worker and bundled FFmpeg, biliup, Deno, and related dependencies, then ship a Tauri NSIS `setup.exe` with WebView2 handling, signing, upgrade and uninstall flows, checksums, and clean-Windows acceptance tests. End users should not need to install Python, Rust, Node.js, or FFmpeg.',
        '',
        '### Phase 3: macOS apps and DMGs',
        '',
        'Estimated at **7–11 working days**, targeting `0.4.0`. Produce separate native Apple Silicon and Intel builds, with Keychain integration, Finder launch support, `.app`/DMG layout, nested signing, notarization, and Gatekeeper testing on real Macs. An arm64 build will not stand in for Intel acceptance.',
        '',
        'The combined estimate is **28–41 working days**, excluding certificate applications, platform-review lead time, and major scope changes.',
        '',
        '## Safety boundaries that stay in place',
        '',
        '- Download, validation, and upload each remain single-lane while different stages overlap; there is no upload-concurrency option.',
        '- Complete MP4 files remain untouched; only non-MP4 media is converted, with no automatic quality reduction for UI convenience.',
        '- Failed validation can never reach upload, and task media is cleaned only after a BV ID is returned.',
        '- An unknown submission result moves into a review state instead of being retried blindly.',
        '- `repair` only prepares replacement media; it never submits again or changes the original BV ID.',
        '- The CLI remains available and shares the same business layer and submission constraints as the desktop app.',
        '',
        'See the [public roadmap](/roadmap) for the phase summary. Actual completion status and future releases are tracked in the [yt2bili GitHub repository](https://github.com/YihanLi-erisaer/yt2bili).',
      ].join('\n'),
    },
  },
  {
    slug: 'yt2bili-incomplete-video-validation-fix',
    date: '2026-09-19',
    title: {
      zh: 'yt2bili：修复不完整视频误上传',
      'zh-HK': 'yt2bili：修復不完整影片誤上傳',
      en: 'yt2bili: preventing incomplete video uploads',
    },
    excerpt: {
      zh:
        '修复 `.part` 半成品被误判为完整文件的问题，新增上传前完整解码校验、损坏文件隔离与安全清理流程。',
      'zh-HK':
        '修復 `.part` 半成品被誤判為完整檔案的問題，新增上傳前完整解碼驗證、損壞檔案隔離與安全清理流程。',
      en:
        'Fixed partial `.part` downloads being mistaken for complete media, with full pre-upload decode validation, quarantine, and safer cleanup.',
    },
    body: {
      zh: [
        '这次问题的根本原因是：**未下载完整的视频被程序误判为完整文件并上传了。**',
        '',
        '## 问题定位',
        '',
        '旧代码会把 `.part` 半成品直接改名，并主要依赖文件头中的时长信息判断文件是否完整。补上完整音频后，容器显示的总时长可能看起来正常，但实际画面已经提前截断：',
        '',
        '- 第一条视频应为 **85 分 27 秒**，实际画面只有 **48 分 36 秒**。',
        '- 第二条视频应为 **40 分 4 秒**，实际画面只有 **34 分 56 秒**。',
        '',
        '旧逻辑还会在发现已有 `video.mp4` 时跳过检查，导致损坏文件被反复复用。目前没有证据表明单纯使用 AV1 就是此次失败的原因。',
        '',
        '## 修复内容',
        '',
        '- 不再擅自把 `.part` 文件当作成品，续传和最终改名交由下载器完成。',
        '- 上传前完整解码检查画面、音频及各自时长；发现损坏文件后先隔离，再重新下载。',
        '- 完整、有效的 MP4 文件直接上传，不强制转码。',
        '- 仅在上传成功并取得 BV 号后删除当前任务文件；上传失败或试运行时保留文件。',
        '',
        '## 验证状态',
        '',
        '**29 项测试已通过。** 两条完整源文件已重新下载并通过校验，原转码任务已经停止。当前尚未重新上传，因此 B 站侧的最终处理结果仍待验证。',
      ].join('\n'),
      'zh-HK': [
        '這次問題的根本原因是：**未下載完整的影片被程式誤判為完整檔案並上傳了。**',
        '',
        '## 問題定位',
        '',
        '舊程式碼會把 `.part` 半成品直接重新命名，並主要依賴檔案頭中的時長資訊判斷檔案是否完整。補上完整音訊後，容器顯示的總時長可能看起來正常，但實際畫面已經提前截斷：',
        '',
        '- 第一條影片應為 **85 分 27 秒**，實際畫面只有 **48 分 36 秒**。',
        '- 第二條影片應為 **40 分 4 秒**，實際畫面只有 **34 分 56 秒**。',
        '',
        '舊邏輯還會在發現已有 `video.mp4` 時略過檢查，導致損壞檔案被反覆重用。目前沒有證據顯示單純使用 AV1 就是此次失敗的原因。',
        '',
        '## 修復內容',
        '',
        '- 不再擅自把 `.part` 檔案當作成品，續傳和最終重新命名交由下載器完成。',
        '- 上傳前完整解碼檢查畫面、音訊及各自時長；發現損壞檔案後先隔離，再重新下載。',
        '- 完整、有效的 MP4 檔案直接上傳，不強制轉碼。',
        '- 僅在上傳成功並取得 BV 號後刪除目前任務檔案；上傳失敗或試運行時保留檔案。',
        '',
        '## 驗證狀態',
        '',
        '**29 項測試已通過。** 兩條完整來源檔案已重新下載並通過驗證，原轉碼任務已經停止。目前尚未重新上傳，因此 B 站端的最終處理結果仍待驗證。',
      ].join('\n'),
      en: [
        'The root cause was straightforward: **an incomplete download was mistaken for a complete video and uploaded.**',
        '',
        '## Root cause',
        '',
        'The old code renamed `.part` files as finished media and relied mainly on duration metadata from the file header. After a complete audio track was added, the container duration could look correct even though the video stream ended early:',
        '',
        '- The first video should have been **85:27**, but its picture ended at **48:36**.',
        '- The second should have been **40:04**, but its picture ended at **34:56**.',
        '',
        'The old path also skipped validation whenever `video.mp4` already existed, so a damaged file could be reused repeatedly. There is no evidence that AV1 alone caused this failure.',
        '',
        '## Fix',
        '',
        '- `.part` files are no longer promoted manually; the downloader now owns resume and final rename behavior.',
        '- Video and audio are fully decoded and their durations checked before upload. Damaged media is quarantined and downloaded again.',
        '- A complete, valid MP4 is uploaded directly without forced transcoding.',
        '- Files for the current task are deleted only after a successful upload returns a BV ID. Failed uploads and dry runs keep their files.',
        '',
        '## Verification status',
        '',
        '**All 29 tests pass.** Both source videos have been downloaded again and validated, and the old transcode jobs were stopped. They have not yet been uploaded again, so the final Bilibili processing result is still pending.',
      ].join('\n'),
    },
  },
  {
    slug: 'yt2bili-pipeline-and-commit-history',
    date: '2026-09-03',
    title: {
      zh: 'yt2bili：从第一次提交到 Windows 下载锁',
      'zh-HK': 'yt2bili：從第一次提交到 Windows 下載鎖',
      en: 'yt2bili: from first import to the Windows download lock',
    },
    excerpt: {
      zh:
        '根据 GitHub README 与全部 10 次提交，说明 yt2bili 如何把有权转载的 YouTube 视频下载、翻译并排队投稿到 B 站。',
      'zh-HK':
        '根據 GitHub README 與全部 10 次提交，說明 yt2bili 如何把有權轉載的 YouTube 影片下載、翻譯並排隊投稿到 B 站。',
      en:
        'From the README and all 10 GitHub commits: how yt2bili downloads authorized YouTube videos, translates metadata, and queues Bilibili uploads.',
    },
    body: {
      zh: [
        '产品页：[yt2bili](/products/yt2bili)。源码与提交见 [YihanLi-erisaer/yt2bili](https://github.com/YihanLi-erisaer/yt2bili)（截至 2026-09-03 共 **10** 次提交）。',
        '',
        'yt2bili 是本地 **Python CLI**，不是网站后台。它只应用于你拥有版权、已获授权、或源平台明确允许转载的视频。流水线在投稿前会停在 `--dry-run`；正式投稿走 Web 投稿，创作声明为「内容无需标注」，简介末尾带上原标题、原作者和原链接。',
        '',
        '## README 里的流水线',
        '',
        '1. 解析 YouTube 元数据。',
        '2. 下载最高可用画质；已是 MP4 则跳过转码。',
        '3. 封面裁成 1280×720 JPEG，失败则抽帧。',
        '4. DeepL Free 翻译标题与简介（已是中文则跳过），标题截到 80 字。',
        '5. 调用官方 [biliupR](https://github.com/biliup/biliup/releases/latest) 提交。',
        '',
        '产物在 `work/<video_id>/`，任务在 `data/tasks.sqlite`。投稿成功后会删掉该稿件的本地媒体，任务行仍保留。非正式会员大约每天最多 5 条；不要对同一账号并行打开多个上传进程。',
        '',
        '## 代码怎么拆',
        '',
        '- `cli.py`：`setup` / `login` / `renew` / `youtube-cookies` / `list` / `run` / `retry`。',
        '- `pipeline.py`：阶段编排、Windows 下载锁、翻译锁、上传锁、按任务日志。',
        '- `youtube.py`：yt-dlp、Cookie、JS 运行时、416 修复、格式排序。',
        '- `media.py`：FFmpeg/ffprobe、封面、抽帧、音视频合并。',
        '- `translate.py`：DeepL；`bili_upload.py`：Web 投稿参数；`db.py`：SQLite。',
        '',
        '## 提交历史（新 → 旧）',
        '',
        '- **[49d6a84](https://github.com/YihanLi-erisaer/yt2bili/commit/49d6a84308f83304aecec497a73d8cc22bd58749)**（2026-09-03）— Windows 默认并行下载改为 1 路；下载锁、`.part` 重命名重试、文件占用 / SSL 错误提示。',
        '- **[ff21324](https://github.com/YihanLi-erisaer/yt2bili/commit/ff2132495910df54cac08e6c5de2432cec419211)**（2026-08-31）— ffprobe 探测时长；复用完整本地分片；缺音轨时下载音频再 mux；416 后从本地视频修复。',
        '- **[4e2def3](https://github.com/YihanLi-erisaer/yt2bili/commit/4e2def30bd0e0f6f5312f3e4418582b1d7952c6c)**（2026-08-30）— 识别 HTTP 416，清掉 `*.part` / `*.ytdl` 再重试。',
        '- **[14ef55d](https://github.com/YihanLi-erisaer/yt2bili/commit/14ef55d71ffdc8801a53b16e8fba9fda1360e2d7)**（2026-08-29）— 优先 `web_embedded` 以拿到更高 DASH；记录所选格式；嵌入受限时提示可能只有 1080p。',
        '- **[7f769b4](https://github.com/YihanLi-erisaer/yt2bili/commit/7f769b4dc9c83d524a998412e68e1631e53de83e)**（2026-08-29）— `youtube-cookies`、Node/Deno JS 运行时检测、yt-dlp 升到 2026.8.19。',
        '- **[74a16a0](https://github.com/YihanLi-erisaer/yt2bili/commit/74a16a08b8f66f2be7fdee4ebbba736977e0b82a)**（2026-08-29）— 批量链接：并行下载、上传排队、`--file` / `-j`、已投稿批量跳过。',
        '- **[a614334](https://github.com/YihanLi-erisaer/yt2bili/commit/a614334f4ceac9e33065a818141abd122ac5bfd8)**（2026-08-29）— 改为 Web 投稿：`--submit web`、`--no-reprint 0`。',
        '- **[33536f1](https://github.com/YihanLi-erisaer/yt2bili/commit/33536f1c6fa073effd01bd0d4ae239fa25a8fdbc)**（2026-08-29）— 投稿成功后删除 `work/` 下本地文件。',
        '- **[0b0c8b9](https://github.com/YihanLi-erisaer/yt2bili/commit/0b0c8b9dcac1a4e70d0b8e29612c1dc543cb5388)**（2026-08-29）— 创作声明改为「内容无需标注」；源文件已是 MP4 则复制、不重编码。',
        '- **[5586eba](https://github.com/YihanLi-erisaer/yt2bili/commit/5586eba74cdc083317a48ea99deab989d32099b0)**（2026-08-29）— 初始导入：CLI、yt-dlp、FFmpeg/Pillow、DeepL、biliup、SQLite。',
        '',
        '## 怎么跟进',
        '',
        '- 产品介绍：[yt2bili](/products/yt2bili)。',
        '- 安装与参数：[README](https://github.com/YihanLi-erisaer/yt2bili#readme)。',
        '- Issue：[仓库 Issues](https://github.com/YihanLi-erisaer/yt2bili/issues)。',
      ].join('\n'),
      'zh-HK': [
        '產品頁：[yt2bili](/products/yt2bili)。原始碼與提交見 [YihanLi-erisaer/yt2bili](https://github.com/YihanLi-erisaer/yt2bili)（截至 2026-09-03 共 **10** 次提交）。',
        '',
        'yt2bili 是本機 **Python CLI**，不是網站後台。它只應用於你擁有版權、已獲授權、或來源平台明確允許轉載的影片。流水線在投稿前會停在 `--dry-run`；正式投稿走 Web 投稿，創作聲明為「內容無需標註」，簡介末尾帶上原標題、原作者和原連結。',
        '',
        '## README 裡的流水線',
        '',
        '1. 解析 YouTube 中繼資料。',
        '2. 下載最高可用畫質；已是 MP4 則跳過轉碼。',
        '3. 封面裁成 1280×720 JPEG，失敗則抽幀。',
        '4. DeepL Free 翻譯標題與簡介（已是中文則跳過），標題截到 80 字。',
        '5. 呼叫官方 [biliupR](https://github.com/biliup/biliup/releases/latest) 提交。',
        '',
        '產物在 `work/<video_id>/`，任務在 `data/tasks.sqlite`。投稿成功後會刪掉該稿件的本機媒體，任務列仍保留。非正式會員大約每天最多 5 條；不要對同一帳號並行開啟多個上傳行程。',
        '',
        '## 程式碼怎麼拆',
        '',
        '- `cli.py`：`setup` / `login` / `renew` / `youtube-cookies` / `list` / `run` / `retry`。',
        '- `pipeline.py`：階段編排、Windows 下載鎖、翻譯鎖、上傳鎖、依任務日誌。',
        '- `youtube.py`：yt-dlp、Cookie、JS 執行階段、416 修復、格式排序。',
        '- `media.py`：FFmpeg/ffprobe、封面、抽幀、音訊合併。',
        '- `translate.py`：DeepL；`bili_upload.py`：Web 投稿參數；`db.py`：SQLite。',
        '',
        '## 提交歷史（新 → 舊）',
        '',
        '- **[49d6a84](https://github.com/YihanLi-erisaer/yt2bili/commit/49d6a84308f83304aecec497a73d8cc22bd58749)**（2026-09-03）— Windows 預設並行下載改為 1 路；下載鎖、`.part` 重新命名重試、檔案占用 / SSL 錯誤提示。',
        '- **[ff21324](https://github.com/YihanLi-erisaer/yt2bili/commit/ff2132495910df54cac08e6c5de2432cec419211)**（2026-08-31）— ffprobe 探測時長；複用完整本機分片；缺音軌時下載音訊再 mux；416 後從本機影片修復。',
        '- **[4e2def3](https://github.com/YihanLi-erisaer/yt2bili/commit/4e2def30bd0e0f6f5312f3e4418582b1d7952c6c)**（2026-08-30）— 辨識 HTTP 416，清掉 `*.part` / `*.ytdl` 再重試。',
        '- **[14ef55d](https://github.com/YihanLi-erisaer/yt2bili/commit/14ef55d71ffdc8801a53b16e8fba9fda1360e2d7)**（2026-08-29）— 優先 `web_embedded` 以拿到更高 DASH；記錄所選格式；嵌入受限時提示可能只有 1080p。',
        '- **[7f769b4](https://github.com/YihanLi-erisaer/yt2bili/commit/7f769b4dc9c83d524a998412e68e1631e53de83e)**（2026-08-29）— `youtube-cookies`、Node/Deno JS 執行階段偵測、yt-dlp 升到 2026.8.19。',
        '- **[74a16a0](https://github.com/YihanLi-erisaer/yt2bili/commit/74a16a08b8f66f2be7fdee4ebbba736977e0b82a)**（2026-08-29）— 批次連結：並行下載、上傳排隊、`--file` / `-j`、已投稿批次跳過。',
        '- **[a614334](https://github.com/YihanLi-erisaer/yt2bili/commit/a614334f4ceac9e33065a818141abd122ac5bfd8)**（2026-08-29）— 改為 Web 投稿：`--submit web`、`--no-reprint 0`。',
        '- **[33536f1](https://github.com/YihanLi-erisaer/yt2bili/commit/33536f1c6fa073effd01bd0d4ae239fa25a8fdbc)**（2026-08-29）— 投稿成功後刪除 `work/` 下本機檔案。',
        '- **[0b0c8b9](https://github.com/YihanLi-erisaer/yt2bili/commit/0b0c8b9dcac1a4e70d0b8e29612c1dc543cb5388)**（2026-08-29）— 創作聲明改為「內容無需標註」；來源檔已是 MP4 則複製、不重編碼。',
        '- **[5586eba](https://github.com/YihanLi-erisaer/yt2bili/commit/5586eba74cdc083317a48ea99deab989d32099b0)**（2026-08-29）— 初始匯入：CLI、yt-dlp、FFmpeg/Pillow、DeepL、biliup、SQLite。',
        '',
        '## 怎麼跟進',
        '',
        '- 產品介紹：[yt2bili](/products/yt2bili)。',
        '- 安裝與參數：[README](https://github.com/YihanLi-erisaer/yt2bili#readme)。',
        '- Issue：[倉庫 Issues](https://github.com/YihanLi-erisaer/yt2bili/issues)。',
      ].join('\n'),
      en: [
        'Product page: [yt2bili](/products/yt2bili). Source and history: [YihanLi-erisaer/yt2bili](https://github.com/YihanLi-erisaer/yt2bili) (**10** commits as of 2026-09-03).',
        '',
        'yt2bili is a **local Python CLI**, not a hosted backend. Use it only for videos you own, have permission to reuse, or that the source platform explicitly allows you to republish. `--dry-run` stops before submit. Live submits use Bilibili’s web mode with the “内容无需标注” declaration and append original title, uploader, and URL to the description.',
        '',
        '## Pipeline from the README',
        '',
        '1. Resolve YouTube metadata.',
        '2. Download the highest available quality; skip transcode if the file is already MP4.',
        '3. Crop the cover to 1280×720 JPEG, or extract a frame on failure.',
        '4. Translate title and description with DeepL Free (skip if already Chinese); cap the title at 80 characters.',
        '5. Submit with official [biliupR](https://github.com/biliup/biliup/releases/latest).',
        '',
        'Artifacts live in `work/<video_id>/`; tasks live in `data/tasks.sqlite`. After a successful submit the local media for that job is deleted; the task row stays. Non-member accounts are roughly limited to five posts a day. Do not run multiple upload processes against the same account.',
        '',
        '## How the code is split',
        '',
        '- `cli.py`: `setup` / `login` / `renew` / `youtube-cookies` / `list` / `run` / `retry`.',
        '- `pipeline.py`: stages, Windows download lock, translate lock, upload lock, per-task logs.',
        '- `youtube.py`: yt-dlp, cookies, JS runtime, 416 repair, format sort.',
        '- `media.py`: FFmpeg/ffprobe, covers, frames, audio mux.',
        '- `translate.py`: DeepL; `bili_upload.py`: web-submit flags; `db.py`: SQLite.',
        '',
        '## Commit history (newest first)',
        '',
        '- **[49d6a84](https://github.com/YihanLi-erisaer/yt2bili/commit/49d6a84308f83304aecec497a73d8cc22bd58749)** (2026-09-03) — Windows default download jobs = 1; download lock; `.part` rename retries; file-lock / SSL messages.',
        '- **[ff21324](https://github.com/YihanLi-erisaer/yt2bili/commit/ff2132495910df54cac08e6c5de2432cec419211)** (2026-08-31) — ffprobe duration checks; reuse complete local parts; mux missing audio; repair after 416.',
        '- **[4e2def3](https://github.com/YihanLi-erisaer/yt2bili/commit/4e2def30bd0e0f6f5312f3e4418582b1d7952c6c)** (2026-08-30) — Detect HTTP 416, delete `*.part` / `*.ytdl`, retry.',
        '- **[14ef55d](https://github.com/YihanLi-erisaer/yt2bili/commit/14ef55d71ffdc8801a53b16e8fba9fda1360e2d7)** (2026-08-29) — Prefer `web_embedded` for higher DASH; log selected format; warn when embed limits you to 1080p.',
        '- **[7f769b4](https://github.com/YihanLi-erisaer/yt2bili/commit/7f769b4dc9c83d524a998412e68e1631e53de83e)** (2026-08-29) — `youtube-cookies`, Node/Deno JS runtime detection, yt-dlp 2026.8.19.',
        '- **[74a16a0](https://github.com/YihanLi-erisaer/yt2bili/commit/74a16a08b8f66f2be7fdee4ebbba736977e0b82a)** (2026-08-29) — Batch URLs: parallel downloads, queued uploads, `--file` / `-j`, skip already-submitted items in batch.',
        '- **[a614334](https://github.com/YihanLi-erisaer/yt2bili/commit/a614334f4ceac9e33065a818141abd122ac5bfd8)** (2026-08-29) — Web submit: `--submit web`, `--no-reprint 0`.',
        '- **[33536f1](https://github.com/YihanLi-erisaer/yt2bili/commit/33536f1c6fa073effd01bd0d4ae239fa25a8fdbc)** (2026-08-29) — Delete `work/` media after a successful upload.',
        '- **[0b0c8b9](https://github.com/YihanLi-erisaer/yt2bili/commit/0b0c8b9dcac1a4e70d0b8e29612c1dc543cb5388)** (2026-08-29) — Declaration “内容无需标注”; copy existing MP4 instead of re-encoding.',
        '- **[5586eba](https://github.com/YihanLi-erisaer/yt2bili/commit/5586eba74cdc083317a48ea99deab989d32099b0)** (2026-08-29) — Initial import: CLI, yt-dlp, FFmpeg/Pillow, DeepL, biliup, SQLite.',
        '',
        '## Where to follow along',
        '',
        '- Product page: [yt2bili](/products/yt2bili).',
        '- Setup: [README](https://github.com/YihanLi-erisaer/yt2bili#readme).',
        '- Issues: [repo Issues](https://github.com/YihanLi-erisaer/yt2bili/issues).',
      ].join('\n'),
    },
  },
  {
    slug: 'smeeting-release-and-deploy-history',
    date: '2026-04-27',
    title: {
      zh: 'smeeting 开发版本历史（Releases 与网站部署）',
      'zh-HK': 'smeeting 開發版本歷史（Releases 與網站部署）',
      en: 'smeeting release history (GitHub Releases & site deployments)',
    },
    excerpt: {
      zh:
        '按 GitHub Releases 上的版本号列出目前全部 20 个发行版说明（新→旧），并附网站部署说明。',
      'zh-HK':
        '按 GitHub Releases 上的版本號列出目前全部 20 個發行版說明（新→舊），並附網站部署說明。',
      en:
        'Every smeeting GitHub Release (20 tags, newest first) with notes, plus how the StarDazz site deploys.',
    },
    body: {
      zh: [
        '产品页 [smeeting](/products/smeeting) 的 **Release** 区提供 **Google Play** 与 [`app-release.apk` 直链](https://github.com/YihanLi-erisaer/smeeting/releases/latest/download/app-release.apk)。**以下变更说明均摘自** [smeeting Releases](https://github.com/YihanLi-erisaer/smeeting) **对应版本的发行正文**（截至文档整理时共 **20** 个 Release，顺序为 **新→旧**）。',
        '',
        '本站页面由 [stardazz.com](https://github.com/YihanLi-erisaer/stardazz.com) 仓库构建，部署记录见 [**Deployments**](https://github.com/YihanLi-erisaer/stardazz.com/deployments)，与 Android APK 节奏独立。',
        '',
        '## 全部 Release（按版本号 · 新→旧）',
        '',
        '- **[v4.1.4](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v4.1.4)**（Latest）— 修复Google Play版本可能无法使用AI总结功能**。',
        '- **[v4.1.3](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v4.1.3)** — 优化 AI 摘要场景下的**语言识别准确度**。',
        '- **[v4.1.2](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v4.1.2)** — 修复 ASR 转写中**新一句可能覆盖上一句**的问题。',
        '- **[v4.1.1](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v4.1.1)** — 下载 AI 模型时**保持亮屏**；生成摘要时让转写区域**跳到最新输出位置**。',
        '- **[v4.1.0](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v4.1.0)** — **显著提升**摘要推理速度与准确度；LLM 框架由 llama-cpp 换为 **ncnn**；模型换为 **Qwen3.0 0.6B**；设置页**不再显示** ASR 运行于 CPU 或 GPU；修复「打开应用摘要一次后无法再次摘要、需重启」的问题。（Release 中附 **Full Changelog**：v3.3.16…v4.1.0）',
        '- **[v4.0.6-beta](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v4.0.6-beta)**（预发布）— 修复**中国大陆**环境下无法下载模型文件的问题。',
        '- **[v4.0.5-beta](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v4.0.5-beta)**（预发布）— 增加**删除模型**；生成摘要时保持亮屏；修复取消摘要后再次点「重新摘要」无法启动、**文本过长导致崩溃**等问题。',
        '- **[v4.0.0-beta](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v4.0.0-beta)**（预发布）— **LLM 摘要 Beta**：已可运行摘要，仍有性能与小问题；**中文**等语言支持增强。',
        '- **[v3.3.16](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v3.3.16)** — 标题注明为「**仅语音转写**的最后一版稳定能力」：主界面 UI **自适应**不同屏幕尺寸；修复**系统导航栏**显示问题。',
        '- **[v3.3.15](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v3.3.15)** — **浅色/深色主题**可随系统变化；转写详情页可选中**指定文本片段**。',
        '- **[v3.3.13](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v3.3.13)** — 历史记录中可**全屏**查看单条转写；更换 **图标与应用名称**。',
        '- **[v3.3.10](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v3.3.10)** — **聆听时保持亮屏**；结果区域满时可**自动向下滚动**；**性能**优化。',
        '- **[v3.3.7](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v3.3.7)** — **性能**改进；修复模型可能被**重复初始化**的问题。',
        '- **[v3.3.1](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v3.3.1)** — 优化**启动流程**，启动模块更稳健；修复启动过程中的**崩溃**。',
        '- **[v3.3.0](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v3.3.0)** — 支持 **GPU 推理**（不可用时回退 CPU）；调整**历史与设置**页按钮布局。',
        '- **[v3.2.2](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v3.2.2)** — **标点算法**优化（v3.2.2）。',
        '- **[v3.2.1](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v3.2.1)** — 调整历史页的**文案、按钮图标与 UI**。',
        '- **[v.3.2.0](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v.3.2.0)** — **转写历史页**：本地存储全部转写；历史页可复制或删除**单条**转写。（标签名为 `v.3.2.0`）',
        '- **[v.3.1.0](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v.3.1.0)** — 本版说明：历史页模块已加入并可从主页进入（Release 标题注明历史页在本版**尚不可访问**、其余功能正常；标签名为 `v.3.1.0`）。',
        '- **[v3.0.0](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v3.0.0)** — **启动优化**：缩短初始化时间，加快模型加载并可更快开始转写。',
        '- **[v2.4.0](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v2.4.0)** — 设置中可在 **Beam search** 与默认 **Greedy search** 之间选择。',
        '',
        '## 如何跟进',
        '',
        '- **安装**：Play 商店与 Release APK 见 [产品页](/products/smeeting)。',
        '- **Android 反馈**：[smeeting Issues](https://github.com/YihanLi-erisaer/smeeting/issues)。',
        '- **官网 / Dev Blog**：[stardazz.com 仓库](https://github.com/YihanLi-erisaer/stardazz.com) · [Deployments](https://github.com/YihanLi-erisaer/stardazz.com/deployments)。',
      ].join('\n'),
      'zh-HK': [
        '產品頁 [smeeting](/products/smeeting) 的 **Release** 區提供 **Google Play** 與 [`app-release.apk` 直連](https://github.com/YihanLi-erisaer/smeeting/releases/latest/download/app-release.apk)。**以下變更說明均摘自** [smeeting Releases](https://github.com/YihanLi-erisaer/smeeting) **對應版本的發行正文**（截至整理時共 **20** 個 Release，順序為 **新→舊**）。',
        '',
        '本站頁面由 [stardazz.com](https://github.com/YihanLi-erisaer/stardazz.com) 存放庫建置，部署紀錄見 [**Deployments**](https://github.com/YihanLi-erisaer/stardazz.com/deployments)，與 Android APK 節奏獨立。',
        '',
        '## 全部 Release（按版本號 · 新→舊）',
        '',
        '- **[v4.1.4](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v4.1.4)**（Latest）— 修復 Google Play 版本可能無法使用 AI 總結功能的問題。',
        '- **[v4.1.3](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v4.1.3)**— 最佳化 AI 摘要場景下的**語言辨識準確度**。',
        '- **[v4.1.2](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v4.1.2)** — 修復 ASR 轉寫中**新一句可能覆蓋上一句**的問題。',
        '- **[v4.1.1](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v4.1.1)** — 下載 AI 模型時**保持螢幕亮起**；產生摘要時讓轉寫區域**跳到最新輸出位置**。',
        '- **[v4.1.0](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v4.1.0)** — **顯著提升**摘要推理速度與準確度；LLM 框架由 llama-cpp 改為 **ncnn**；模型改為 **Qwen3.0 0.6B**；設定頁**不再顯示** ASR 運行於 CPU 或 GPU；修復「開啟應用程式摘要一次後無法再次摘要、需重啟」的問題。（Release 附 **Full Changelog**：v3.3.16…v4.1.0）',
        '- **[v4.0.6-beta](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v4.0.6-beta)**（預發佈）— 修復**中國大陸**環境下無法下載模型檔案的問題。',
        '- **[v4.0.5-beta](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v4.0.5-beta)**（預發佈）— 新增**刪除模型**；產生摘要時保持螢幕亮起；修復取消摘要後再按「重新摘要」無法啟動、**文字過長導致當機**等問題。',
        '- **[v4.0.0-beta](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v4.0.0-beta)**（預發佈）— **LLM 摘要 Beta**：已可運行摘要，仍有效能與小問題；**中文**等語言支援增強。',
        '- **[v3.3.16](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v3.3.16)** — 標題註明為「**僅語音轉寫**」的最後一版穩定能力：主畫面 UI **自適應**不同螢幕尺寸；修復**系統導覽列**顯示問題。',
        '- **[v3.3.15](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v3.3.15)** — **淺色/深色主題**可隨系統變化；轉寫詳情頁可選取**指定文字片段**。',
        '- **[v3.3.13](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v3.3.13)** — 紀錄中可**全螢幕**檢視單筆轉寫；更換 **圖示與應用程式名稱**。',
        '- **[v3.3.10](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v3.3.10)** — **聆聽時保持螢幕亮起**；結果區域滿時可**自動向下捲動**；**效能**最佳化。',
        '- **[v3.3.7](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v3.3.7)** — **效能**改進；修復模型可能被**重複初始化**的問題。',
        '- **[v3.3.1](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v3.3.1)** — 最佳化**啟動流程**，啟動模組更穩健；修復啟動過程中的**當機**。',
        '- **[v3.3.0](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v3.3.0)** — 支援 **GPU 推理**（不可用時回退 CPU）；調整**紀錄與設定**頁按鈕版面。',
        '- **[v3.2.2](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v3.2.2)** — **標點演算法**最佳化（v3.2.2）。',
        '- **[v3.2.1](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v3.2.1)** — 調整紀錄頁的**字串、按鈕圖示與 UI**。',
        '- **[v.3.2.0](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v.3.2.0)** — **轉寫紀錄頁**：本機儲存全部轉寫；紀錄頁可複製或刪除**單筆**轉寫。（標籤名為 `v.3.2.0`）',
        '- **[v.3.1.0](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v.3.1.0)** — 本版說明：紀錄頁模組已加入並可從主頁進入（Release 標題註明紀錄頁在本版**尚不可存取**、其餘功能正常；標籤名為 `v.3.1.0`）。',
        '- **[v3.0.0](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v3.0.0)** — **啟動最佳化**：縮短初始化時間，加快模型載入並可更快開始轉寫。',
        '- **[v2.4.0](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v2.4.0)** — 設定中可在 **Beam search** 與預設 **Greedy search** 之間選擇。',
        '',
        '## 如何跟進',
        '',
        '- **安裝**：Play 商店與 Release APK 見 [產品頁](/products/smeeting)。',
        '- **Android 回饋**：[smeeting Issues](https://github.com/YihanLi-erisaer/smeeting/issues)。',
        '- **官網 / Dev Blog**：[stardazz.com 存放庫](https://github.com/YihanLi-erisaer/stardazz.com) · [Deployments](https://github.com/YihanLi-erisaer/stardazz.com/deployments)。',
      ].join('\n'),
      en: [
        'The [smeeting product page](/products/smeeting) links **Google Play** and the [`app-release.apk` direct download](https://github.com/YihanLi-erisaer/smeeting/releases/latest/download/app-release.apk). **Every bullet below quotes the published notes** for that tag on [smeeting Releases](https://github.com/YihanLi-erisaer/smeeting) (**20** releases total at the time of writing, **newest first**).',
        '',
        'This site is built from the [stardazz.com](https://github.com/YihanLi-erisaer/stardazz.com) repo; deploy history lives under [**Deployments**](https://github.com/YihanLi-erisaer/stardazz.com/deployments), separate from the Android APK cadence.',
        '',
        '## All releases (by version, newest first)',
        '',
        '- **[v4.1.4](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v4.1.4)** (Latest) — Fix **AI summary** not working in Google Play version.',
        '- **[v4.1.3](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v4.1.3)** — Optimize **language recognition accuracy** in AI summary.',
        '- **[v4.1.2](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v4.1.2)** — Fix ASR where a **new utterance may cover** the previous one.',
        '- **[v4.1.1](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v4.1.1)** — **Keep screen on** while downloading the AI model; **scroll the transcription box** to the newest output while the model generates a summary.',
        '- **[v4.1.0](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v4.1.0)** — **Much faster, more accurate** summary inference; LLM stack moved to **ncnn** (replacing llama-cpp); model **Qwen3.0 0.6B**; **removed** CPU/GPU ASR labels in Settings; fixed “summarize once, cannot re-summarize until app restart”. (**Full Changelog** on the release: v3.3.16…v4.1.0.)',
        '- **[v4.0.6-beta](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v4.0.6-beta)** (Pre-release) — Fix model download in **mainland China**.',
        '- **[v4.0.5-beta](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v4.0.5-beta)** (Pre-release) — **Delete model**; keep screen on while generating summary; fix re-summarize after cancel; fix **crash on very long** text.',
        '- **[v4.0.0-beta](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v4.0.0-beta)** (Pre-release) — **LLM summary beta** (usable, with perf issues and small bugs); more **Chinese** support.',
        '- **[v3.3.16](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v3.3.16)** — Titled **last stable speech-to-text-only** line: **responsive** main UI; fix **system navigation bar** display.',
        '- **[v3.3.15](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v3.3.15)** — **Light/dark theme** can follow the system; select a **specific text chunk** on the transcription detail page.',
        '- **[v3.3.13](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v3.3.13)** — History can open a transcription **full screen**; **icon and app name** updated.',
        '- **[v3.3.10](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v3.3.10)** — **Keep screen on** while listening; result box **auto-scrolls** when full; **performance** work.',
        '- **[v3.3.7](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v3.3.7)** — **Performance**; fix **double model initialization**.',
        '- **[v3.3.1](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v3.3.1)** — **Startup** flow more robust; fix **crashes during startup**.',
        '- **[v3.3.0](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v3.3.0)** — **GPU inference** with CPU fallback; **history & settings** button layout.',
        '- **[v3.2.2](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v3.2.2)** — **Punctuation algorithm** improvements.',
        '- **[v3.2.1](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v3.2.1)** — History page **strings, icons, and UI** tweaks.',
        '- **[v.3.2.0](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v.3.2.0)** — **Transcription history** stored locally; copy or delete **single** items. (Tag spelled `v.3.2.0`.)',
        '- **[v.3.1.0](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v.3.1.0)** — Release title: history page **not reachable** in this build, other features OK; notes mention adding the history module from the main page. (Tag spelled `v.3.1.0`.)',
        '- **[v3.0.0](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v3.0.0)** — **Startup optimization**: faster init, faster model load, quicker path to transcription.',
        '- **[v2.4.0](https://github.com/YihanLi-erisaer/smeeting/releases/tag/v2.4.0)** — Choose **Beam search** vs default **Greedy search** in Settings.',
        '',
        '## Where to follow along',
        '',
        '- **Install**: Play + APK on the [product page](/products/smeeting).',
        '- **Android**: [smeeting Issues](https://github.com/YihanLi-erisaer/smeeting/issues).',
        '- **Website**: [stardazz.com repo](https://github.com/YihanLi-erisaer/stardazz.com) · [Deployments](https://github.com/YihanLi-erisaer/stardazz.com/deployments).',
      ].join('\n'),
    },
  },
  {
    slug: 'smeeting-progress-update',
    date: '2026-04-01',
    title: {
      zh: 'smeeting 近期开发进展',
      'zh-HK': 'smeeting 近期開發進展',
      en: 'Recent smeeting progress',
    },
    excerpt: {
      zh:
        '隐私政策、主题切换、交互式 UI 预览与下载入口等更新，以及后续性能与可访问性计划。',
      'zh-HK':
        '隱私權政策、主題切換、互動式 UI 預覽與下載入口等更新，以及後續效能與無障礙計畫。',
      en:
        'Privacy page, theme switcher, interactive UI preview, download flow—and what is next for performance and a11y.',
    },
    body: {
      zh: [
        '这一迭代里，我们主要围绕**合规与体验**做了几件事：',
        '',
        '- 上线独立的**隐私政策**页面，说明麦克风、转写与本地模型的数据边界。',
        '- 站点与产品侧支持**浅色 / 深色主题**，减少长时间阅读的疲劳。',
        '- 增加**应用界面预览**（网页演示），方便在商店外快速了解主要界面状态。',
        '- 优化 **GitHub Releases / 下载**相关入口，让试用路径更直观。',
        '',
        '## 接下来',
        '',
        '会继续打磨 **性能**（启动、转写与摘要延迟）以及 **可访问性**（焦点、对比度与屏幕阅读器友好度）。欢迎在 [GitHub](https://github.com/YihanLi-erisaer/smeeting) 提 issue。',
      ].join('\n'),
      'zh-HK': [
        '這一迭代裡，我們主要圍繞**合規與體驗**做了幾件事：',
        '',
        '- 上線獨立的**隱私權政策**頁面，說明麥克風、轉寫與本機模型的資料邊界。',
        '- 網站與產品側支援**淺色 / 深色主題**，減少長時間閱讀的疲勞。',
        '- 增加**應用程式介面預覽**（網頁演示），方便在商店外快速了解主要介面狀態。',
        '- 最佳化 **GitHub Releases / 下載**相關入口，讓試用路徑更直觀。',
        '',
        '## 接下來',
        '',
        '會繼續打磨 **效能**（啟動、轉寫與摘要延遲）以及 **無障礙**（焦點、對比度與螢幕閱讀器友善度）。歡迎在 [GitHub](https://github.com/YihanLi-erisaer/smeeting) 提 issue。',
      ].join('\n'),
      en: [
        'This cycle focused on **compliance and UX**:',
        '',
        '- Shipped a dedicated **privacy policy** page (mic, transcripts, on-device models).',
        '- Added **light/dark theme** across the site and product-facing surfaces.',
        '- Built an **in-app UI preview** (web mock-up) so people can skim flows before install.',
        '- Improved **GitHub Releases / download** entry points for a clearer try-out path.',
        '',
        '## Next',
        '',
        'We will keep tightening **performance** (cold start, ASR/summary latency) and **accessibility** (focus, contrast, screen-reader ergonomics). Issues welcome on [GitHub](https://github.com/YihanLi-erisaer/smeeting).',
      ].join('\n'),
    },
  },
  {
    slug: 'roadmap-next-steps',
    date: '2026-03-15',
    title: {
      zh: '下一阶段计划',
      'zh-HK': '下一階段計畫',
      en: 'What comes next',
    },
    excerpt: {
      zh: '更多开发日志、技术细节与里程碑公开，以及功能迭代的透明路线。',
      'zh-HK':
        '更多開發日誌、技術細節與里程碑公開，以及功能迭代的透明路線。',
      en:
        'More dev logs, technical write-ups, milestone posts, and a clearer public roadmap.',
    },
    body: {
      zh: [
        'Dev Blog 会从此前「静态公告」改成**可跳转的多篇文章**结构：每篇文章在代码里用 Markdown 维护，前端统一渲染。',
        '',
        '## 你在这里会看到',
        '',
        '- 版本亮点与**工程权衡**（为什么这样设计、放弃了什么）。',
        '- **性能与端侧模型**相关的实测笔记。',
        '- 与 smeeting 路线图对齐的**里程碑**更新。',
        '',
        '若有希望优先覆盖的主题，欢迎通过 GitHub 或邮件反馈。',
      ].join('\n'),
      'zh-HK': [
        'Dev Blog 會從此前「靜態公告」改成**可跳轉的多篇文章**結構：每篇文章在程式碼裡用 Markdown 維護，前端統一渲染。',
        '',
        '## 您在這裡會看到',
        '',
        '- 版本亮點與**工程權衡**（為什麼這樣設計、放棄了什麼）。',
        '- **效能與裝置端模型**相關的實測筆記。',
        '- 與 smeeting 路線圖對齊的**里程碑**更新。',
        '',
        '若有希望優先涵蓋的主題，歡迎透過 GitHub 或郵件回饋。',
      ].join('\n'),
      en: [
        'The dev blog is now a **real index + post** setup: each article is Markdown in the repo and rendered on the site.',
        '',
        '## You can expect',
        '',
        '- Release notes with **engineering trade-offs** (what we picked and what we skipped).',
        '- Notes on **on-device models and performance** with real measurements.',
        '- **Milestone updates** aligned with the smeeting roadmap.',
        '',
        'If you want a topic covered first, ping us on GitHub or email.',
      ].join('\n'),
    },
  },
]

export function getDevBlogPostBySlug(slug: string): DevBlogPost | undefined {
  return DEV_BLOG_POSTS.find((p) => p.slug === slug)
}

export function getDevBlogPostsSorted(): DevBlogPost[] {
  return [...DEV_BLOG_POSTS].sort((a, b) => (a.date < b.date ? 1 : -1))
}
